/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['Comment.js']) {
  _$jscoverage['Comment.js'] = [];
  _$jscoverage['Comment.js'][1] = 0;
  _$jscoverage['Comment.js'][2] = 0;
  _$jscoverage['Comment.js'][4] = 0;
  _$jscoverage['Comment.js'][8] = 0;
  _$jscoverage['Comment.js'][9] = 0;
  _$jscoverage['Comment.js'][10] = 0;
  _$jscoverage['Comment.js'][11] = 0;
  _$jscoverage['Comment.js'][12] = 0;
  _$jscoverage['Comment.js'][13] = 0;
  _$jscoverage['Comment.js'][14] = 0;
  _$jscoverage['Comment.js'][15] = 0;
  _$jscoverage['Comment.js'][17] = 0;
  _$jscoverage['Comment.js'][18] = 0;
  _$jscoverage['Comment.js'][19] = 0;
  _$jscoverage['Comment.js'][20] = 0;
  _$jscoverage['Comment.js'][22] = 0;
  _$jscoverage['Comment.js'][27] = 0;
  _$jscoverage['Comment.js'][29] = 0;
  _$jscoverage['Comment.js'][34] = 0;
  _$jscoverage['Comment.js'][36] = 0;
  _$jscoverage['Comment.js'][39] = 0;
  _$jscoverage['Comment.js'][44] = 0;
  _$jscoverage['Comment.js'][46] = 0;
  _$jscoverage['Comment.js'][47] = 0;
}
_$jscoverage['Comment.js'].source = ["\"use strict\";","Object.defineProperties(exports, {","  Comment: {get: function() {","      return Comment;","    }},","  __esModule: {value: true}","});","var $__Object$defineProperty = Object.defineProperty;","var $__Object$create = Object.create;","var escapeHTML = require('./utils/escapeHTML');","var Node = require('./Node').Node;","var Comment = function($__super) {","  \"use strict\";","  function Comment(comment) {","    this._value = comment;","  }","  Comment.__proto__ = ($__super !== null ? $__super : Function.prototype);","  Comment.prototype = $__Object$create(($__super !== null ? $__super.prototype : null));","  $__Object$defineProperty(Comment.prototype, \"constructor\", {value: Comment});","  $__Object$defineProperty(Comment.prototype, \"innerHTML\", {","    get: function() {","      return '';","    },","    enumerable: true,","    configurable: true","  });","  $__Object$defineProperty(Comment.prototype, \"outerHTML\", {","    get: function() {","      return '&lt;!--' + escapeHTML(this._value) + '--&gt;';","    },","    enumerable: true,","    configurable: true","  });","  $__Object$defineProperty(Comment.prototype, \"data\", {","    get: function() {","      return this._value;","    },","    set: function(data) {","      this._value = data;","    },","    enumerable: true,","    configurable: true","  });","  return Comment;","}(Node);","Object.defineProperty(Comment.prototype, 'nodeType', {value: Node.COMMENT_NODE});","Object.defineProperty(Comment.prototype, 'nodeName', {value: '#comment'});","","//# sourceMappingURL=Comment.js.map"];
_$jscoverage['Comment.js'][1]++;
"use strict";
_$jscoverage['Comment.js'][2]++;
Object.defineProperties(exports, {Comment: {get: (function () {
  _$jscoverage['Comment.js'][4]++;
  return Comment;
})}, __esModule: {value: true}});
_$jscoverage['Comment.js'][8]++;
var $__Object$defineProperty = Object.defineProperty;
_$jscoverage['Comment.js'][9]++;
var $__Object$create = Object.create;
_$jscoverage['Comment.js'][10]++;
var escapeHTML = require("./utils/escapeHTML");
_$jscoverage['Comment.js'][11]++;
var Node = require("./Node").Node;
_$jscoverage['Comment.js'][12]++;
var Comment = (function ($__super) {
  _$jscoverage['Comment.js'][13]++;
  "use strict";
  _$jscoverage['Comment.js'][14]++;
  function Comment(comment) {
    _$jscoverage['Comment.js'][15]++;
    this._value = comment;
}
  _$jscoverage['Comment.js'][17]++;
  Comment.__proto__ = (($__super !== null)? $__super: Function.prototype);
  _$jscoverage['Comment.js'][18]++;
  Comment.prototype = $__Object$create((($__super !== null)? $__super.prototype: null));
  _$jscoverage['Comment.js'][19]++;
  $__Object$defineProperty(Comment.prototype, "constructor", {value: Comment});
  _$jscoverage['Comment.js'][20]++;
  $__Object$defineProperty(Comment.prototype, "innerHTML", {get: (function () {
  _$jscoverage['Comment.js'][22]++;
  return "";
}), enumerable: true, configurable: true});
  _$jscoverage['Comment.js'][27]++;
  $__Object$defineProperty(Comment.prototype, "outerHTML", {get: (function () {
  _$jscoverage['Comment.js'][29]++;
  return ("<!--" + escapeHTML(this._value) + "-->");
}), enumerable: true, configurable: true});
  _$jscoverage['Comment.js'][34]++;
  $__Object$defineProperty(Comment.prototype, "data", {get: (function () {
  _$jscoverage['Comment.js'][36]++;
  return this._value;
}), set: (function (data) {
  _$jscoverage['Comment.js'][39]++;
  this._value = data;
}), enumerable: true, configurable: true});
  _$jscoverage['Comment.js'][44]++;
  return Comment;
})(Node);
_$jscoverage['Comment.js'][46]++;
Object.defineProperty(Comment.prototype, "nodeType", {value: Node.COMMENT_NODE});
_$jscoverage['Comment.js'][47]++;
Object.defineProperty(Comment.prototype, "nodeName", {value: "#comment"});
