/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['DocumentFragment.js']) {
  _$jscoverage['DocumentFragment.js'] = [];
  _$jscoverage['DocumentFragment.js'][1] = 0;
  _$jscoverage['DocumentFragment.js'][2] = 0;
  _$jscoverage['DocumentFragment.js'][4] = 0;
  _$jscoverage['DocumentFragment.js'][8] = 0;
  _$jscoverage['DocumentFragment.js'][9] = 0;
  _$jscoverage['DocumentFragment.js'][10] = 0;
  _$jscoverage['DocumentFragment.js'][11] = 0;
  _$jscoverage['DocumentFragment.js'][12] = 0;
  _$jscoverage['DocumentFragment.js'][13] = 0;
  _$jscoverage['DocumentFragment.js'][14] = 0;
  _$jscoverage['DocumentFragment.js'][15] = 0;
  _$jscoverage['DocumentFragment.js'][16] = 0;
  _$jscoverage['DocumentFragment.js'][17] = 0;
  _$jscoverage['DocumentFragment.js'][18] = 0;
  _$jscoverage['DocumentFragment.js'][20] = 0;
  _$jscoverage['DocumentFragment.js'][21] = 0;
  _$jscoverage['DocumentFragment.js'][22] = 0;
  _$jscoverage['DocumentFragment.js'][23] = 0;
  _$jscoverage['DocumentFragment.js'][25] = 0;
  _$jscoverage['DocumentFragment.js'][30] = 0;
  _$jscoverage['DocumentFragment.js'][32] = 0;
}
_$jscoverage['DocumentFragment.js'].source = ["\"use strict\";","Object.defineProperties(exports, {","  DocumentFragment: {get: function() {","      return DocumentFragment;","    }},","  __esModule: {value: true}","});","var $__Object$defineProperty = Object.defineProperty;","var $__Object$create = Object.create;","var $__Object$getPrototypeOf = Object.getPrototypeOf;","var Node = require('./Node').Node;","var ParentNode = require('./ParentNode').ParentNode;","var DocumentFragment = function($__super) {","  \"use strict\";","  function DocumentFragment() {","    var $__0 = $__Object$getPrototypeOf(DocumentFragment.prototype);","    if ($__0 !== null)","      $__0.constructor.apply(this, arguments);","  }","  DocumentFragment.__proto__ = ($__super !== null ? $__super : Function.prototype);","  DocumentFragment.prototype = $__Object$create(($__super !== null ? $__super.prototype : null));","  $__Object$defineProperty(DocumentFragment.prototype, \"constructor\", {value: DocumentFragment});","  $__Object$defineProperty(DocumentFragment.prototype, \"outerHTML\", {","    get: function() {","      return this.innerHTML;","    },","    enumerable: true,","    configurable: true","  });","  return DocumentFragment;","}(ParentNode);","Object.defineProperty(DocumentFragment.prototype, 'nodeType', {value: Node.DOCUMENT_FRAGMENT_NODE});","","//# sourceMappingURL=DocumentFragment.js.map"];
_$jscoverage['DocumentFragment.js'][1]++;
"use strict";
_$jscoverage['DocumentFragment.js'][2]++;
Object.defineProperties(exports, {DocumentFragment: {get: (function () {
  _$jscoverage['DocumentFragment.js'][4]++;
  return DocumentFragment;
})}, __esModule: {value: true}});
_$jscoverage['DocumentFragment.js'][8]++;
var $__Object$defineProperty = Object.defineProperty;
_$jscoverage['DocumentFragment.js'][9]++;
var $__Object$create = Object.create;
_$jscoverage['DocumentFragment.js'][10]++;
var $__Object$getPrototypeOf = Object.getPrototypeOf;
_$jscoverage['DocumentFragment.js'][11]++;
var Node = require("./Node").Node;
_$jscoverage['DocumentFragment.js'][12]++;
var ParentNode = require("./ParentNode").ParentNode;
_$jscoverage['DocumentFragment.js'][13]++;
var DocumentFragment = (function ($__super) {
  _$jscoverage['DocumentFragment.js'][14]++;
  "use strict";
  _$jscoverage['DocumentFragment.js'][15]++;
  function DocumentFragment() {
    _$jscoverage['DocumentFragment.js'][16]++;
    var $__0 = $__Object$getPrototypeOf(DocumentFragment.prototype);
    _$jscoverage['DocumentFragment.js'][17]++;
    if (($__0 !== null)) {
      _$jscoverage['DocumentFragment.js'][18]++;
      $__0.constructor.apply(this, arguments);
    }
}
  _$jscoverage['DocumentFragment.js'][20]++;
  DocumentFragment.__proto__ = (($__super !== null)? $__super: Function.prototype);
  _$jscoverage['DocumentFragment.js'][21]++;
  DocumentFragment.prototype = $__Object$create((($__super !== null)? $__super.prototype: null));
  _$jscoverage['DocumentFragment.js'][22]++;
  $__Object$defineProperty(DocumentFragment.prototype, "constructor", {value: DocumentFragment});
  _$jscoverage['DocumentFragment.js'][23]++;
  $__Object$defineProperty(DocumentFragment.prototype, "outerHTML", {get: (function () {
  _$jscoverage['DocumentFragment.js'][25]++;
  return this.innerHTML;
}), enumerable: true, configurable: true});
  _$jscoverage['DocumentFragment.js'][30]++;
  return DocumentFragment;
})(ParentNode);
_$jscoverage['DocumentFragment.js'][32]++;
Object.defineProperty(DocumentFragment.prototype, "nodeType", {value: Node.DOCUMENT_FRAGMENT_NODE});
