/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['Document.js']) {
  _$jscoverage['Document.js'] = [];
  _$jscoverage['Document.js'][1] = 0;
  _$jscoverage['Document.js'][2] = 0;
  _$jscoverage['Document.js'][4] = 0;
  _$jscoverage['Document.js'][8] = 0;
  _$jscoverage['Document.js'][9] = 0;
  _$jscoverage['Document.js'][10] = 0;
  _$jscoverage['Document.js'][11] = 0;
  _$jscoverage['Document.js'][12] = 0;
  _$jscoverage['Document.js'][13] = 0;
  _$jscoverage['Document.js'][14] = 0;
  _$jscoverage['Document.js'][15] = 0;
  _$jscoverage['Document.js'][16] = 0;
  _$jscoverage['Document.js'][17] = 0;
  _$jscoverage['Document.js'][19] = 0;
  _$jscoverage['Document.js'][21] = 0;
  _$jscoverage['Document.js'][26] = 0;
  _$jscoverage['Document.js'][28] = 0;
  _$jscoverage['Document.js'][33] = 0;
  _$jscoverage['Document.js'][35] = 0;
  _$jscoverage['Document.js'][36] = 0;
  _$jscoverage['Document.js'][37] = 0;
  _$jscoverage['Document.js'][42] = 0;
  _$jscoverage['Document.js'][44] = 0;
  _$jscoverage['Document.js'][49] = 0;
  _$jscoverage['Document.js'][51] = 0;
}
_$jscoverage['Document.js'].source = ["\"use strict\";","Object.defineProperties(exports, {","  Document: {get: function() {","      return Document;","    }},","  __esModule: {value: true}","});","var $__Object$defineProperty = Object.defineProperty;","var Node = require('./Node').Node;","var Comment = require('./Comment').Comment;","var DocumentFragment = require('./DocumentFragment').DocumentFragment;","var HTMLElement = require('./HTMLElement').HTMLElement;","var Text = require('./Text').Text;","var Document = function() {","  \"use strict\";","  function Document() {","    this.documentElement = this.createElement('html');","  }","  $__Object$defineProperty(Document.prototype, \"createComment\", {","    value: function(data) {","      return new Comment(data);","    },","    enumerable: false,","    writable: true","  });","  $__Object$defineProperty(Document.prototype, \"createDocumentFragment\", {","    value: function() {","      return new DocumentFragment();","    },","    enumerable: false,","    writable: true","  });","  $__Object$defineProperty(Document.prototype, \"createElement\", {","    value: function(name) {","      var element = new HTMLElement();","      element.nodeName = name;","      return element;","    },","    enumerable: false,","    writable: true","  });","  $__Object$defineProperty(Document.prototype, \"createTextNode\", {","    value: function(textContent) {","      return new Text(textContent);","    },","    enumerable: false,","    writable: true","  });","  return Document;","}();","Object.defineProperty(Document.prototype, 'nodeType', {value: Node.DOCUMENT_NODE});","","//# sourceMappingURL=Document.js.map"];
_$jscoverage['Document.js'][1]++;
"use strict";
_$jscoverage['Document.js'][2]++;
Object.defineProperties(exports, {Document: {get: (function () {
  _$jscoverage['Document.js'][4]++;
  return Document;
})}, __esModule: {value: true}});
_$jscoverage['Document.js'][8]++;
var $__Object$defineProperty = Object.defineProperty;
_$jscoverage['Document.js'][9]++;
var Node = require("./Node").Node;
_$jscoverage['Document.js'][10]++;
var Comment = require("./Comment").Comment;
_$jscoverage['Document.js'][11]++;
var DocumentFragment = require("./DocumentFragment").DocumentFragment;
_$jscoverage['Document.js'][12]++;
var HTMLElement = require("./HTMLElement").HTMLElement;
_$jscoverage['Document.js'][13]++;
var Text = require("./Text").Text;
_$jscoverage['Document.js'][14]++;
var Document = (function () {
  _$jscoverage['Document.js'][15]++;
  "use strict";
  _$jscoverage['Document.js'][16]++;
  function Document() {
    _$jscoverage['Document.js'][17]++;
    this.documentElement = this.createElement("html");
}
  _$jscoverage['Document.js'][19]++;
  $__Object$defineProperty(Document.prototype, "createComment", {value: (function (data) {
  _$jscoverage['Document.js'][21]++;
  return new Comment(data);
}), enumerable: false, writable: true});
  _$jscoverage['Document.js'][26]++;
  $__Object$defineProperty(Document.prototype, "createDocumentFragment", {value: (function () {
  _$jscoverage['Document.js'][28]++;
  return new DocumentFragment();
}), enumerable: false, writable: true});
  _$jscoverage['Document.js'][33]++;
  $__Object$defineProperty(Document.prototype, "createElement", {value: (function (name) {
  _$jscoverage['Document.js'][35]++;
  var element = new HTMLElement();
  _$jscoverage['Document.js'][36]++;
  element.nodeName = name;
  _$jscoverage['Document.js'][37]++;
  return element;
}), enumerable: false, writable: true});
  _$jscoverage['Document.js'][42]++;
  $__Object$defineProperty(Document.prototype, "createTextNode", {value: (function (textContent) {
  _$jscoverage['Document.js'][44]++;
  return new Text(textContent);
}), enumerable: false, writable: true});
  _$jscoverage['Document.js'][49]++;
  return Document;
})();
_$jscoverage['Document.js'][51]++;
Object.defineProperty(Document.prototype, "nodeType", {value: Node.DOCUMENT_NODE});
