/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['HTMLElement.js']) {
  _$jscoverage['HTMLElement.js'] = [];
  _$jscoverage['HTMLElement.js'][1] = 0;
  _$jscoverage['HTMLElement.js'][2] = 0;
  _$jscoverage['HTMLElement.js'][4] = 0;
  _$jscoverage['HTMLElement.js'][8] = 0;
  _$jscoverage['HTMLElement.js'][9] = 0;
  _$jscoverage['HTMLElement.js'][10] = 0;
  _$jscoverage['HTMLElement.js'][11] = 0;
  _$jscoverage['HTMLElement.js'][12] = 0;
  _$jscoverage['HTMLElement.js'][13] = 0;
  _$jscoverage['HTMLElement.js'][14] = 0;
  _$jscoverage['HTMLElement.js'][15] = 0;
  _$jscoverage['HTMLElement.js'][16] = 0;
  _$jscoverage['HTMLElement.js'][17] = 0;
  _$jscoverage['HTMLElement.js'][18] = 0;
  _$jscoverage['HTMLElement.js'][20] = 0;
  _$jscoverage['HTMLElement.js'][21] = 0;
  _$jscoverage['HTMLElement.js'][22] = 0;
  _$jscoverage['HTMLElement.js'][23] = 0;
  _$jscoverage['HTMLElement.js'][25] = 0;
  _$jscoverage['HTMLElement.js'][26] = 0;
  _$jscoverage['HTMLElement.js'][32] = 0;
  _$jscoverage['HTMLElement.js'][34] = 0;
  _$jscoverage['HTMLElement.js'][35] = 0;
  _$jscoverage['HTMLElement.js'][41] = 0;
}
_$jscoverage['HTMLElement.js'].source = ["\"use strict\";","Object.defineProperties(exports, {","  HTMLElement: {get: function() {","      return HTMLElement;","    }},","  __esModule: {value: true}","});","var $__Object$getPrototypeOf = Object.getPrototypeOf;","var $__Object$defineProperty = Object.defineProperty;","var $__Object$create = Object.create;","var Element = require('./Element').Element;","var CSSStyleDeclaration = require('./HTMLElement/CSSStyleDeclaration').CSSStyleDeclaration;","var escapeAttribute = require('./utils/escapeAttribute');","var HTMLElement = function($__super) {","  \"use strict\";","  function HTMLElement() {","    $__Object$getPrototypeOf(HTMLElement.prototype).constructor.call(this);","    this.style = new CSSStyleDeclaration(this);","  }","  HTMLElement.__proto__ = ($__super !== null ? $__super : Function.prototype);","  HTMLElement.prototype = $__Object$create(($__super !== null ? $__super.prototype : null));","  $__Object$defineProperty(HTMLElement.prototype, \"constructor\", {value: HTMLElement});","  $__Object$defineProperty(HTMLElement.prototype, \"_updatedAttribute\", {","    value: function(attributeName, value) {","      if (attributeName === 'style') {","        this.style.cssText = value || '';","      }","    },","    enumerable: false,","    writable: true","  });","  $__Object$defineProperty(HTMLElement.prototype, \"outerHTML\", {","    get: function() {","      return '&lt;' + this.nodeName + Object.keys(this._attributes).reduce(function(value, attributeName) {","        return value + ' ' + attributeName + '=\"' + escapeAttribute(this._attributes[attributeName]) + '\"';","      }.bind(this), '') + '&gt;' + this.innerHTML + '&lt;/' + this.nodeName + '&gt;';","    },","    enumerable: true,","    configurable: true","  });","  return HTMLElement;","}(Element);","","//# sourceMappingURL=HTMLElement.js.map"];
_$jscoverage['HTMLElement.js'][1]++;
"use strict";
_$jscoverage['HTMLElement.js'][2]++;
Object.defineProperties(exports, {HTMLElement: {get: (function () {
  _$jscoverage['HTMLElement.js'][4]++;
  return HTMLElement;
})}, __esModule: {value: true}});
_$jscoverage['HTMLElement.js'][8]++;
var $__Object$getPrototypeOf = Object.getPrototypeOf;
_$jscoverage['HTMLElement.js'][9]++;
var $__Object$defineProperty = Object.defineProperty;
_$jscoverage['HTMLElement.js'][10]++;
var $__Object$create = Object.create;
_$jscoverage['HTMLElement.js'][11]++;
var Element = require("./Element").Element;
_$jscoverage['HTMLElement.js'][12]++;
var CSSStyleDeclaration = require("./HTMLElement/CSSStyleDeclaration").CSSStyleDeclaration;
_$jscoverage['HTMLElement.js'][13]++;
var escapeAttribute = require("./utils/escapeAttribute");
_$jscoverage['HTMLElement.js'][14]++;
var HTMLElement = (function ($__super) {
  _$jscoverage['HTMLElement.js'][15]++;
  "use strict";
  _$jscoverage['HTMLElement.js'][16]++;
  function HTMLElement() {
    _$jscoverage['HTMLElement.js'][17]++;
    $__Object$getPrototypeOf(HTMLElement.prototype).constructor.call(this);
    _$jscoverage['HTMLElement.js'][18]++;
    this.style = new CSSStyleDeclaration(this);
}
  _$jscoverage['HTMLElement.js'][20]++;
  HTMLElement.__proto__ = (($__super !== null)? $__super: Function.prototype);
  _$jscoverage['HTMLElement.js'][21]++;
  HTMLElement.prototype = $__Object$create((($__super !== null)? $__super.prototype: null));
  _$jscoverage['HTMLElement.js'][22]++;
  $__Object$defineProperty(HTMLElement.prototype, "constructor", {value: HTMLElement});
  _$jscoverage['HTMLElement.js'][23]++;
  $__Object$defineProperty(HTMLElement.prototype, "_updatedAttribute", {value: (function (attributeName, value) {
  _$jscoverage['HTMLElement.js'][25]++;
  if ((attributeName === "style")) {
    _$jscoverage['HTMLElement.js'][26]++;
    this.style.cssText = (value || "");
  }
}), enumerable: false, writable: true});
  _$jscoverage['HTMLElement.js'][32]++;
  $__Object$defineProperty(HTMLElement.prototype, "outerHTML", {get: (function () {
  _$jscoverage['HTMLElement.js'][34]++;
  return ("<" + this.nodeName + Object.keys(this._attributes).reduce((function (value, attributeName) {
  _$jscoverage['HTMLElement.js'][35]++;
  return (value + " " + attributeName + "=\"" + escapeAttribute(this._attributes[attributeName]) + "\"");
}).bind(this), "") + ">" + this.innerHTML + "</" + this.nodeName + ">");
}), enumerable: true, configurable: true});
  _$jscoverage['HTMLElement.js'][41]++;
  return HTMLElement;
})(Element);
