/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['index.js']) {
  _$jscoverage['index.js'] = [];
  _$jscoverage['index.js'][1] = 0;
  _$jscoverage['index.js'][2] = 0;
  _$jscoverage['index.js'][3] = 0;
  _$jscoverage['index.js'][4] = 0;
  _$jscoverage['index.js'][5] = 0;
  _$jscoverage['index.js'][6] = 0;
  _$jscoverage['index.js'][7] = 0;
}
_$jscoverage['index.js'].source = ["\"use strict\";","var Document = require('./Document').Document;","global.window = global;","global.document = new Document();","global.Event = require('./Event').Event;","global.Node = require('./Node').Node;","global.DocumentFragment = require('./DocumentFragment').DocumentFragment;","","//# sourceMappingURL=index.js.map"];
_$jscoverage['index.js'][1]++;
"use strict";
_$jscoverage['index.js'][2]++;
var Document = require("./Document").Document;
_$jscoverage['index.js'][3]++;
global.window = global;
_$jscoverage['index.js'][4]++;
global.document = new Document();
_$jscoverage['index.js'][5]++;
global.Event = require("./Event").Event;
_$jscoverage['index.js'][6]++;
global.Node = require("./Node").Node;
_$jscoverage['index.js'][7]++;
global.DocumentFragment = require("./DocumentFragment").DocumentFragment;
