/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['Text.js']) {
  _$jscoverage['Text.js'] = [];
  _$jscoverage['Text.js'][1] = 0;
  _$jscoverage['Text.js'][2] = 0;
  _$jscoverage['Text.js'][4] = 0;
  _$jscoverage['Text.js'][8] = 0;
  _$jscoverage['Text.js'][9] = 0;
  _$jscoverage['Text.js'][10] = 0;
  _$jscoverage['Text.js'][11] = 0;
  _$jscoverage['Text.js'][12] = 0;
  _$jscoverage['Text.js'][13] = 0;
  _$jscoverage['Text.js'][14] = 0;
  _$jscoverage['Text.js'][15] = 0;
  _$jscoverage['Text.js'][16] = 0;
  _$jscoverage['Text.js'][18] = 0;
  _$jscoverage['Text.js'][19] = 0;
  _$jscoverage['Text.js'][20] = 0;
  _$jscoverage['Text.js'][21] = 0;
  _$jscoverage['Text.js'][24] = 0;
  _$jscoverage['Text.js'][31] = 0;
  _$jscoverage['Text.js'][34] = 0;
  _$jscoverage['Text.js'][40] = 0;
  _$jscoverage['Text.js'][42] = 0;
  _$jscoverage['Text.js'][43] = 0;
}
_$jscoverage['Text.js'].source = ["\"use strict\";","Object.defineProperties(exports, {","  Text: {get: function() {","      return Text;","    }},","  __esModule: {value: true}","});","var $__Object$defineProperties = Object.defineProperties;","var $__Object$defineProperty = Object.defineProperty;","var $__Object$create = Object.create;","var escapeHTML = require('./utils/escapeHTML');","var Node = require('./Node').Node;","var Text = function($__super) {","  \"use strict\";","  function Text(textContent) {","    this.value = textContent;","  }","  Text.__proto__ = ($__super !== null ? $__super : Function.prototype);","  Text.prototype = $__Object$create(($__super !== null ? $__super.prototype : null));","  $__Object$defineProperty(Text.prototype, \"constructor\", {value: Text});","  $__Object$defineProperties(Text.prototype, {","    _toHTML: {","      value: function() {","        return escapeHTML(this.value);","      },","      enumerable: false,","      writable: true","    },","    textContent: {","      get: function() {","        return this.value;","      },","      set: function(textContent) {","        this.value = textContent;","      },","      enumerable: true,","      configurable: true","    }","  });","  return Text;","}(Node);","Object.defineProperty(Text.prototype, 'nodeType', {value: Node.TEXT_NODE});","Object.defineProperty(Text.prototype, 'nodeName', {value: '#text'});","","//# sourceMappingURL=Text.js.map"];
_$jscoverage['Text.js'][1]++;
"use strict";
_$jscoverage['Text.js'][2]++;
Object.defineProperties(exports, {Text: {get: (function () {
  _$jscoverage['Text.js'][4]++;
  return Text;
})}, __esModule: {value: true}});
_$jscoverage['Text.js'][8]++;
var $__Object$defineProperties = Object.defineProperties;
_$jscoverage['Text.js'][9]++;
var $__Object$defineProperty = Object.defineProperty;
_$jscoverage['Text.js'][10]++;
var $__Object$create = Object.create;
_$jscoverage['Text.js'][11]++;
var escapeHTML = require("./utils/escapeHTML");
_$jscoverage['Text.js'][12]++;
var Node = require("./Node").Node;
_$jscoverage['Text.js'][13]++;
var Text = (function ($__super) {
  _$jscoverage['Text.js'][14]++;
  "use strict";
  _$jscoverage['Text.js'][15]++;
  function Text(textContent) {
    _$jscoverage['Text.js'][16]++;
    this.value = textContent;
}
  _$jscoverage['Text.js'][18]++;
  Text.__proto__ = (($__super !== null)? $__super: Function.prototype);
  _$jscoverage['Text.js'][19]++;
  Text.prototype = $__Object$create((($__super !== null)? $__super.prototype: null));
  _$jscoverage['Text.js'][20]++;
  $__Object$defineProperty(Text.prototype, "constructor", {value: Text});
  _$jscoverage['Text.js'][21]++;
  $__Object$defineProperties(Text.prototype, {_toHTML: {value: (function () {
  _$jscoverage['Text.js'][24]++;
  return escapeHTML(this.value);
}), enumerable: false, writable: true}, textContent: {get: (function () {
  _$jscoverage['Text.js'][31]++;
  return this.value;
}), set: (function (textContent) {
  _$jscoverage['Text.js'][34]++;
  this.value = textContent;
}), enumerable: true, configurable: true}});
  _$jscoverage['Text.js'][40]++;
  return Text;
})(Node);
_$jscoverage['Text.js'][42]++;
Object.defineProperty(Text.prototype, "nodeType", {value: Node.TEXT_NODE});
_$jscoverage['Text.js'][43]++;
Object.defineProperty(Text.prototype, "nodeName", {value: "#text"});
