/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['utils/escapeHTML.js']) {
  _$jscoverage['utils/escapeHTML.js'] = [];
  _$jscoverage['utils/escapeHTML.js'][1] = 0;
  _$jscoverage['utils/escapeHTML.js'][2] = 0;
  _$jscoverage['utils/escapeHTML.js'][3] = 0;
  _$jscoverage['utils/escapeHTML.js'][4] = 0;
  _$jscoverage['utils/escapeHTML.js'][6] = 0;
}
_$jscoverage['utils/escapeHTML.js'].source = ["\"use strict\";","module.exports = function(string) {","  if (!string) {","    return string;","  }","  return String(string).replace(/&amp;(?!\\w+;)/g, '&amp;amp;').replace(/&lt;/g, '&amp;lt;').replace(/&gt;/g, '&amp;gt;');","};","","//# sourceMappingURL=../utils/escapeHTML.js.map"];
_$jscoverage['utils/escapeHTML.js'][1]++;
"use strict";
_$jscoverage['utils/escapeHTML.js'][2]++;
module.exports = (function (string) {
  _$jscoverage['utils/escapeHTML.js'][3]++;
  if ((! string)) {
    _$jscoverage['utils/escapeHTML.js'][4]++;
    return string;
  }
  _$jscoverage['utils/escapeHTML.js'][6]++;
  return String(string).replace(/&(?!\w+;)/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
});
